import turtle

pen = turtle.Pen()

def plano():
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.backward(200)
    pen.right(90)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)
    pen.forward(20)
    pen.circle(1)

plano()
